### PR TITLE
Improve the template

### PR DESCRIPTION
**Pull request by tbg**
- Rename "closed" to "merged" (closed PRs are ignored already)
- Show author instead of committer (which is bors) for merged PRs
- Collapse Commits section by default
- Show the repo in the PR description
- Hide PR+commit messages by default for merged PRs

The last item is a mildly opinionated stance: since the newly opened PRs
are shown first, they are evidently supposed to be more interesting to the
reader. When a PR merges, the digest affords a second chance to take a look
at it, but presumably the reader already knows the PR from an earlier
digest, so by default it ought to be collapsed.

### CODE REVIEW

**Comment by tbg** [comment]
New PR, default view

image

Expanded commits:

image

Merged PRs, default view:

image

Merged PR, expanded

image

**Comment by knz** [comment]
LGTM

but you can maybe add a `width: 100%` somewhere so that they all fill the view. We have currently a staircase effect in mails?

**Comment by tbg** [comment]
TFTR!

For the record: we chatted on slack and the table already has `width:100%`. We weren't sure exactly what to do here and decided to not hold up the PR on it.

**Comment by tbg** [comment]
@bobvawter I ran `./push.sh` and it failed

```
+ apt-get install ssmtp -y
Reading package lists...
Building dependency tree...
Reading state information...
Package ssmtp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ssmtp' has no installation candidate
The command '/bin/sh -c docker/build.sh' returned a non-zero code: 100
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 100

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.builds.submit) build 41b09337-f263-4513-8468-47d8a31b78cc completed with status "FAILURE"
```

**Comment by tbg** [comment]
Filed the above as https://github.com/cockroachdb/dev-inf/issues/76

**Pull request merged**
